;(function(){'use strict';var yn=MugineRequire("Utils/Module"),zn=MugineRequire("Text/TextField"),An=MugineRequire("Utils/Plugin"),Bn=MugineRequire("Geom/Color");function Cn(){Cn.j.constructor.apply(this,arguments);this.Wi="";this.yh=this.Xi=null}yn.extend(Cn,zn);Cn.prototype.K="Text";
Cn.Jb=function(a,b){function c(){c.j.constructor.apply(this,arguments);this.Wi=f;this.yh=g;if(e.hintColor)this.Xi=Bn.parse(e.hintColor);else{var a=this.Fd.ed.clone();a.Sl(.5);this.Xi=a}this.$a("")}var d=zn.Jb(a,b);yn.extend(d,Cn);var e=a.param,f=e.textContent,g=e.inputType;yn.extend(c,d);return c};yn.H("Text.InputBox",Cn);An.Zd(2031,Cn);var Dn=MugineRequire("Utils/Module"),En=MugineRequire("Utils/Browser"),Fn=MugineRequire("Render/RenderObjectTextField"),Hn=MugineRequire("Render/StyleSheet"),In=MugineRequire("Utils/Plugin"),Jn=MugineRequire("Render/RenderObject");function Kn(){Kn.j.constructor.apply(this,arguments)}Dn.extend(Kn,Fn);Jn.Qa=function(a){return Jn.gg[a]};var Ln=Kn.prototype;
Ln.Oa=function(){var a=this.c,b=this.Xs(),c=a.Fd,d=a.u.wa,e="";d.mb&&0<d.mb.ga&&(e+=En.prefix.f+"text-stroke:"+d.Nb/1+"px "+d.mb.Db()+";");c=Hn.U("position: absolute; outline: none; padding: 0; background: transparent; border-radius: 0; border: 0; width: "+a.ta+"px; height: "+a.sa+"px;"+En.prefix.f+"transform-origin: left top;"+En.prefix.f+"appearance:none;"+En.prefix.f+"user-select: initial;"+e+"font-family: "+c.Nj+";text-align: "+c.Ug+";color: "+c.ed.Db()+";font-size: "+d.Cb+"px;"+(c.Dj?"font-weight: bold;":
"")+(c.cm?"text-decoration: underline;":"")+(c.ak?"font-style: italic;":"")+(a.Jd?"cursor: pointer;":""));this.va.push(c);this.kd=c;e="color: "+a.Xi.Db();if(En.Xh.OE)var f=c+"::-webkit-input-placeholder";else En.Xh.kD?f=19>parseInt(En.Xh.version)?c+":-moz-placeholder":c+"::-moz-placeholder":En.Xh.Wv&&(f=c+":-ms-input-placeholder");Hn.U(f,e);"textArea"==a.yh?(e="","0"==b.lineHeight?e="normal":b.lineHeight&&(e="line-height:"+b.lineHeight+"px;"),this.fa='<textArea ondragstart="return false;" data-type="input-box" data-mid="'+
a.o+'"'+(a.W?' data-guid="'+a.W+'"':"")+' class="{{className}}" placeholder="'+unescape(a.Wi)+'"style="'+e+'"></textArea>'):(e=(b=0<=["date","time"].indexOf(a.yh))?"value":"placeholder",f=unescape(a.Wi),b&&f&&a.$a(f),this.fa='<input ondragstart="return false;" data-type="input-box" data-mid="'+a.o+'"'+(a.W?' data-guid="'+a.W+'"':"")+' class="{{className}}" type="'+a.yh+'" '+e+'="'+f+'"/>')};Ln.ou=function(){return this.Z().tagName};var Mn=null;
Ln.Dy=function(){var a=document.getElementById("_AnalogInput"),b=document.getElementById("_AnalogArea"),c=Jn.Qa(0).Z();a||(a=document.createElement("span"),a.style.zIndex="10",a.style.position="absolute",a.style.left="-9999px",a.id="_AnalogInput",c.appendChild(a));b||(b=document.createElement("textarea"),b.style.zIndex="10",b.style.position="absolute",b.style.left="-9999px",b.id="_AnalogArea",b.style.height="0",c.appendChild(b))};
Ln.Qb=function(){Kn.j.Qb.apply(this,arguments);this.Z().addEventListener("change",this.ty.bind(this));this.Z().addEventListener("input",this.NA.bind(this));this.Z().addEventListener("focus",this.Ty.bind(this));this.Z().addEventListener("click",this.yy.bind(this));this.Dy()};Ln.Xs=function(){var a=this.c.A.param;return{importLimit:a.importLimit,limitCharset:a.limitCharset,lengthItem:a.lengthItem,lengthLimit:a.lengthLimit,lineHeight:a.inputLineheight}};
Ln.PA=function(a){var b=this.Z(),c=this.Xs(),d=b.value;if(!c.importLimit&&!c.lengthItem||"0"==c.importLimit&&"0"==c.lengthItem)a&&a(d);else{var e=!1,f=document.getElementById("_AnalogInput"),g=document.getElementById("_AnalogArea"),h=this.ou();if(c.importLimit)switch(c.importLimit){case "1":var k=d.match(/[\u4e00-\u9fa5]/gi)||[],k=k.join("");k!=d&&(d=k,Mugeda.messageBox("\u8bf7\u53ea\u8f93\u5165\u4e2d\u6587\u3002",null,function(){a&&a(d)}),e=!0);break;case "2":k=d.match(/[a-z]/gi)||[];k=k.join("");
k!=d&&(d=k,Mugeda.messageBox("\u8bf7\u53ea\u8f93\u5165\u82f1\u6587\u3002",null,function(){a&&a(d)}),e=!0);break;case "4":if(c.limitCharset){k=c.limitCharset;c.limitCharset+="\n";for(var l=!1,n=0;n<d.length;)-1==c.limitCharset.indexOf(d[n])?(d=d.replace(d[n],""),l=!0):n++;l&&(Mugeda.messageBox("\u8bf7\u53ea\u8f93\u5165\u5982\u4e0b\u5b57\u7b26\uff1a\uff08"+k+"\uff09",null,function(){a&&a(d)}),e=!0)}}if(!e)if("INPUT"==h){if(d=d.replace(/\s/gi,"&nbsp;"),f.innerHTML=d,d=d.replace(/\&nbsp;/g," "),g=b.offsetWidth,
b=f.offsetWidth,c.lengthItem&&0!=c.lengthItem)switch(c.lengthItem){case "1":b=parseInt(c.lengthLimit);c.lengthLimit&&d.length>b&&(d=d.substr(0,b),f.innerHTML=d,Mugeda.messageBox("\u6700\u591a\u53ef\u4ee5\u8f93\u5165 "+b+" \u4e2a\u5b57\u7b26\u3002",null,function(){a&&a(d)}),e=!0);break;case "2":if(b>g)for(c=0;c<d.length;c++)b>g&&(d=d.substring(0,d.length-1),f.innerHTML=d,b=f.offsetWidth,Mugeda.messageBox("\u8f93\u5165\u8d85\u51fa\u4e86\u5141\u8bb8\u7684\u957f\u5ea6\u8303\u56f4\u3002",null,function(){a&&
a(d)}),e=!0)}}else if("TEXTAREA"==h&&c.lengthItem&&0!=c.lengthItem)switch(c.lengthItem){case "1":b=parseInt(c.lengthLimit);c.lengthLimit&&d.length>b&&(d=d.substr(0,b));g.value=d;break;case "2":g.value=d,f=parseInt(window.getComputedStyle(b).lineHeight)||39,Math.round(g.scrollHeight/f)>=Math.round(b.scrollHeight/f)?g.value=Mn:Mn=d}!e&&a&&a(d)}};Ln.NA=function(){};Ln.yy=function(){var a=this.Z();document.activeElement!=a&&a.focus()};
Ln.Ty=function(){var a=this.Z(),b=this.ou(),c=document.getElementById("_AnalogInput"),d=document.getElementById("_AnalogArea"),e=window.getComputedStyle(a);"INPUT"==b?(c.style.font=e.font,c.style.transform=e.transform,c.style.left="-9999px"):"TEXTAREA"==b&&(d.style.font=e.font,d.style.transform=e.transform,d.style.overflowY="hidden",d.style.width=a.offsetWidth+"px",d.style.padding=0,d.style.border="none",d.style.left="-9999px")};
Ln.ty=function(){var a=this,b=a.Z(),c=b.value;a.PA(function(d){c!=d&&(b.value=d,b.focus(),b.select());a.c.$a(d)})};Ln.s=function(){var a=this.Z();if(document.activeElement==a){var b=a.getBoundingClientRect(),a=b.top,c=b.bottom,b=Dn.Dk(),a=(a+c)/2,b=b.height,c=this.c.Ya().S.Nf;if(0>a||a>b)c.style.cssText+=En.prefix.f+"transform: translateY(-200px);"}};Ln.ua=function(a,b,c){var d=this.c;Kn.j.constructor.j.ua.apply(this,arguments);d=d.ub();d!=this.ha.value&&(this.ha.value=d)};In.$d(2031,Kn);
})();